feat: added start cmd and healthcheck method.
trustbloc/ace pull request #5
Opened 2022-03-08 16:50 UTC by vkubiv

Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>

2022-03-08 17:31 UTC, aholovko requested changes

2022-03-08 17:31 UTC, aholovko commented on cmd/gatekeeper/startcmd/start.go
> +	"strconv"
plz fix grouping + enable linter for cmd

2022-03-09 14:44 UTC, fqutishat approved these changes

2022-03-09 14:49 UTC, aholovko requested changes

2022-03-09 14:49 UTC, aholovko commented on cmd/gatekeeper/startcmd/start.go
> +		Short: "Starts a comparator server",
fix: gatekeeper

2022-03-09 14:49 UTC, aholovko commented on go.mod
> +	github.com/hyperledger/aries-framework-go v0.1.7
update AFGO version

2022-03-09 15:00 UTC, aholovko approved these changes

2022-03-09 15:00 UTC, merged